In [ ]:
def square(num):
  return num**2
object_ =square(9)
print("The square root of the number is:",object_)

The square root of the number is: 81


In [ ]:
def square(my_list):
  squares = []
  for i in my_list:
     squares.append(i**2)
  return squares
list_ =[45,52,13]
result =square(list_)
print("Sqaures of the list is:",result)


      

Sqaures of the list is: [2025, 2704, 169]


In [3]:
lambda_ = lambda argument1,argument2:argument1 + argument2;
print("Value of the function is:",lambda_(20,30))
print("Value of the function is:",lambda_(40,50))

Value of the function is: 50
Value of the function is: 90


In [9]:
import numpy as np
from time import process_time
python_list = [i for i in range(10000)]
start_time  = process_time()
python_list = [i+5 for i in python_list]
end_time    = process_time()
print(end_time - start_time)


0.001522309000000277


In [10]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array == 5
end_time = process_time()
print(end_time - start_time)

0.0016371060000004434


In [11]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [16]:
b = np.array(([1,2,3,4],[5,6,7,8]))
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
y = np.ones((3,3))
print(y)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [23]:
a = np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
